# Generated by Django 6.0.5 on 2026-07-04 10:00

from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='reservered',
            field=models.BooleanField(default=False),
        ),
    ]
